import { NextRequest, NextResponse } from 'next/server';
import { getDailyBriefing } from '@/lib/storage/supabase-client';

export async function POST(req: NextRequest) {
  try {
    const { format, target } = await req.json(); // format: 'markdown' | 'html' | 'json'; target: 'notion' | 'telegram' | 'email' | 'discord'
    const briefing = await getDailyBriefing();

    if (format === 'markdown') {
      const mdContent = `# ${briefing.title}\n*Date: ${briefing.date}*\n\n` +
        `## Executive Summary\n${briefing.summary}\n\n` +
        `## Top Headlines\n` +
        briefing.topHeadlines.map((h, i) => `${i + 1}. **${h.title}**\n   - *Category:* ${h.category}\n   - *Why it matters:* ${h.examRelevance.whyItMatters}\n`).join('\n') +
        `\n## UPSC High-Yield Revision Notes\n` +
        briefing.revisionNotes.map(n => `- ${n}`).join('\n') +
        `\n\n*Generated by DailyIntel AI Platform*`;

      return NextResponse.json({
        success: true,
        channel: target,
        message: `Successfully formatted briefing for ${target}`,
        payload: mdContent
      });
    }

    return NextResponse.json({
      success: true,
      channel: target,
      message: `Briefing notification sent to ${target} queue successfully.`
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
