'use client';

import React, { useState } from 'react';
import { X, Share2, CheckCircle2, Copy, FileText, Send } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose }) => {
  const [selectedChannel, setSelectedChannel] = useState<'notion' | 'telegram' | 'email' | 'discord' | 'whatsapp'>('notion');
  const [copied, setCopied] = useState(false);
  const [exported, setExported] = useState(false);

  if (!isOpen) return null;

  const handleCopyMarkdown = () => {
    const text = `# Morning Intelligence Brief — 22 July 2026\n\n` +
      `## Key Highlights\n` +
      `- DRDO VSHORADS Air Defence Test\n` +
      `- RBI Repo Rate Held at 6.50%\n` +
      `- India-France Safran 110kN Engine ToT Deal\n` +
      `- Cabinet Approves Rs 10,372 Cr IndiaAI Mission (10k GPUs)\n` +
      `- Gaganyaan TV-D2 Abort Test 100% Success\n\n` +
      `*Generated by DailyIntel AI Platform*`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportTrigger = async () => {
    setExported(true);
    try {
      await fetch('/api/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ format: 'markdown', target: selectedChannel })
      });
    } catch (e) {}
    setTimeout(() => setExported(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="relative w-full max-w-md rounded-2xl border border-bloomberg-border bg-bloomberg-card p-6 shadow-2xl space-y-5">
        <div className="flex items-center justify-between border-b border-bloomberg-border pb-3">
          <h3 className="text-sm font-bold text-white flex items-center gap-2 font-mono">
            <Share2 size={16} className="text-intel-400" />
            EXPORT DAILY BRIEFING & NOTES
          </h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white">
            <X size={18} />
          </button>
        </div>

        <div className="space-y-3 text-xs">
          <label className="font-semibold text-slate-300 block font-mono">Select Export Channel:</label>
          <div className="grid grid-cols-2 gap-2">
            {[
              { id: 'notion', label: '📓 Notion Page', desc: 'Sync to Notion DB' },
              { id: 'telegram', label: '✈️ Telegram Channel', desc: 'Post to Channel' },
              { id: 'email', label: '📧 Morning Email', desc: 'Send PDF / HTML' },
              { id: 'discord', label: '💬 Discord Webhook', desc: 'Post to Server' },
              { id: 'whatsapp', label: '📱 WhatsApp Digest', desc: 'Send Quick Text' },
            ].map(item => (
              <button
                key={item.id}
                onClick={() => setSelectedChannel(item.id as any)}
                className={`p-3 rounded-xl border text-left transition-all space-y-1 ${
                  selectedChannel === item.id
                    ? 'border-intel-500 bg-intel-600/20 text-white font-semibold'
                    : 'border-slate-800 bg-slate-900/60 text-slate-400 hover:border-slate-700'
                }`}
              >
                <div className="font-bold">{item.label}</div>
                <div className="text-[10px] text-slate-400">{item.desc}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="pt-2 flex flex-col gap-2">
          <button
            onClick={handleExportTrigger}
            className="w-full py-2.5 rounded-xl bg-intel-600 text-white text-xs font-semibold hover:bg-intel-500 transition-all flex items-center justify-center gap-2 shadow-lg"
          >
            {exported ? (
              <>
                <CheckCircle2 size={16} className="text-emerald-300" />
                Dispatched to {selectedChannel.toUpperCase()}!
              </>
            ) : (
              <>
                <Send size={16} />
                Send Daily Briefing to {selectedChannel.toUpperCase()}
              </>
            )}
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="w-full py-2 rounded-xl border border-slate-800 bg-slate-900 text-slate-300 text-xs font-medium hover:bg-slate-800 transition-all flex items-center justify-center gap-2"
          >
            <Copy size={14} />
            {copied ? 'Copied Markdown to Clipboard!' : 'Copy Raw Markdown Digest'}
          </button>
        </div>
      </div>
    </div>
  );
};
